Raiders of the Lost Docs
RIT-EVT/BMS pull request #16
Opened 2022-12-13 16:25 UTC by mjmagee991

Adds high-level documentation for the current state of the BMS

2022-12-13 16:36 UTC, mjmagee991 commented
![](https://github.trello.services/images/mini-trello-icon.png) [BMS Hand-Off Documentation](https://trello.com/c/B5n7AZCP/51-bms-hand-off-documentation)

2023-01-02 06:51 UTC, AarC10 requested changes

2023-01-02 06:51 UTC, AarC10 commented on include/BMS/dev/BQ76952.hpp
> +    };
Maybe make this more consistent with each other

2023-01-20 01:31 UTC, DeLozM8 requested changes

2023-01-20 01:31 UTC, DeLozM8 commented on docs/source/index.rst
> +The DEV1-BMS project is currently in the hardware bringup phase. Software
```suggestion
The DEV1-BMS project is currently in the hardware bring up phase. Software
```

2023-01-20 01:31 UTC, DeLozM8 commented on include/BMS/BMS.hpp
> +    static constexpr uint16_t OBJECT_DIRECTIONARY_SIZE = 42;
```suggestion
    static constexpr uint16_t OBJECT_DICTIONARY_SIZE = 42;
```

2023-01-20 01:31 UTC, DeLozM8 commented on src/dev/BQ76952.cpp
> + * @param[out] buf THe buffer to populate with data
```suggestion
 * @param[out] buf The buffer to populate with data
```

2023-01-20 01:31 UTC, DeLozM8 commented on targets/BMS/main.cpp
>      // Intialize the logger
```suggestion
    // Initialize the logger
```

2023-01-20 01:31 UTC, DeLozM8 commented on targets/BMS/main.cpp
>      // Intialize the Interlock
```suggestion
    // Initialize the Interlock
```

2023-01-20 01:31 UTC, DeLozM8 commented on targets/BMS/main.cpp
>      // Intialize the alarm pin
```suggestion
    // Initialize the alarm pin
```

2023-01-31 00:17 UTC, AarC10 approved these changes

2023-02-02 03:42 UTC, DeLozM8 approved these changes

2023-02-02 03:45 UTC, cbolles commented
If nothing else, I can say I left lasting impact in terms of shear number of typos.

2023-02-02 18:14 UTC, merged