I'm Yelling Timber
RIT-EVT/BMS pull request #17
Opened 2023-01-06 14:37 UTC by mjmagee991

Replaced BMSLogger with EVT-core's logger
Cleaned up formatting and documentation
Pulled the latest changes from the project template

2023-01-06 14:38 UTC, mjmagee991 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Delete BMSLogger](https://trello.com/c/rygC2ydH/48-delete-bmslogger)

2023-01-20 00:31 UTC, AarC10 requested changes

2023-01-20 00:31 UTC, AarC10 commented on include/dev/BQ76952.hpp
> +     * Contains a mapping between the target cell and the corresponing
```suggestion
     * Contains a mapping between the target cell and the corresponding
```

2023-01-20 00:31 UTC, AarC10 commented on include/dev/SystemDetect.hpp
> +     * Create the system detect device which will work to indentify the
```suggestion
     * Create the system detect device which will work to identify the
```

2023-01-20 00:31 UTC, AarC10 commented on src/BMS.cpp
>      //bmsOK.writePin(EVT::core::IO::GPIO::State::LOW);
Do we need this line of code here

2023-01-20 00:31 UTC, AarC10 commented on src/BMS.cpp
> +            // If the settings did not transfer successfully, transition tp
```suggestion
            // If the settings did not transfer successfully, transition to
```

2023-01-20 00:31 UTC, AarC10 commented on src/BMS.cpp
> +        v = 0;
```suggestion
    memset(cellVoltage, 0, DEV::BQ76952::NUM_CELLS);
```
There are faster ways to zero out the cell voltages than using a for loop

2023-01-20 00:31 UTC, AarC10 commented on src/BQSettingStorage.cpp
>          return CO_ERR_NONE;
Add brackets to make them consistent with the rest of the code

2023-01-20 00:57 UTC, DeLozM8 commented on include/dev/SystemDetect.hpp
>       * @param[in] bikeHeartBeat The heart beat CANopen ID associated with the
```suggestion
     * @param[in] bikeHeartBeat The heartbeat CANopen ID associated with the
```
suggestion to fix in all areas where "heart beat" is written

2023-01-20 00:57 UTC, DeLozM8 commented on targets/system_detect/main.cpp
>      // Intialize the logger
```suggestion
    // Initialize the logger
```

2023-01-24 19:25 UTC, mjmagee991 commented on src/BMS.cpp
>      //bmsOK.writePin(EVT::core::IO::GPIO::State::LOW);
Yes

2023-01-26 17:13 UTC, ActuallyZach approved these changes

2023-01-31 00:16 UTC, AarC10 approved these changes

2023-01-31 03:44 UTC, merged