BMS? More like RTD
RIT-EVT/BMS pull request #21
Opened 2024-02-09 03:47 UTC by mjmagee991

Updated lots of documentation: RTD, README, and inline docs

2024-02-10 00:44 UTC, mjmagee991 commented
![](https://github.trello.services/images/mini-trello-icon.png) [BMS Documentation Update](https://trello.com/c/mi8Z0qGL/164-bms-documentation-update)

2024-02-13 00:12 UTC, ActuallyTaylor requested changes

2024-02-13 00:12 UTC, ActuallyTaylor commented on include/BQSettingStorage.hpp
> +     * checks to make sure settings are not actively being written to.
It would be best if you had an @return because your other Boolean functions have them.

2024-02-16 03:58 UTC, ActuallyTaylor approved these changes
10/10

2024-02-17 15:45 UTC, ol2764RIT commented
great docs

2024-02-17 15:46 UTC, ol2764RIT approved these changes
good

2024-02-17 21:37 UTC, merged